// <auto-generated />
namespace TasksApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201305272156336_AddTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
